### ISSUE TITLE
How is infreqdb different from AWS Athena?

### ISSUE THREAD

**Issue by rlopezro** [turbobytes/infreqdb#1]

**Comment by sajal** [comment]
I did not know about AWS Athena until 5 minutes ago. It probably describes what I'm really trying to do.

**Comment by sajal** [comment]
After playing with Athena, I feel its not the right fit for my use-case. Athena takes 1 second on average for simple queries. That's too slow for my *hot* items use-case.

Athena: `(Run time: 1.19 seconds, Data scanned: 349.77KB) `

To answer your question

> How is infreqdb different from AWS Athena?

infreqdb downloads and caches the partitions locally in a database format which can be queried easily, while Athena is serverless where each partition is downloaded, parsed and queried at runtime.
