### ISSUE TITLE
Not using official AWS SDK

### ISSUE THREAD

**Issue by pjebs** [turbobytes/infreqdb#2]

**Comment by sajal** [comment]
good idea. I will look into it after I make the storage portion pluggable.

**Comment by sajal** [comment]
Now, users can call [NewWithStorage](https://godoc.org/github.com/turbobytes/infreqdb#NewWithStorage) and supply their own implementation of [Storage](https://godoc.org/github.com/turbobytes/infreqdb#Storage)

They can use whatever SDK they prefer, actually they can use any storage provider they want.
